#!/usr/bin/env bash

# make necessary directories
mkdir -p data/qc/fastp/failed/

# default parallel job count (can override with NUM_JOBS)
num_jobs="${NUM_JOBS:-4}"

# ───────────────────────────────────────────────
# Step 1: Run fastp
# ───────────────────────────────────────────────

# check that there are at least 2 arguments
if [ "$#" -lt 2 ]; then
    echo "Usage: $0 <name_of_substrate> <condition1> [condition2 ...]"
    echo "Example: $0 streptavidin Probe 0w 1w 3w"
    exit 1
fi

# take in the arguments (no shift)
name_of_substrate="$1"
conditions=("${@:2}")   # everything after the first argument

cmd_file="cmds/fastp_${name_of_substrate}.cmds"

# Check that the command file exists
if [ ! -s "$cmd_file" ]; then
    echo "Error: command file '$cmd_file' not found or empty."
    exit 1
fi

echo "Running fastp for ${name_of_substrate}..."
cat "$cmd_file" | parallel --bar -j${num_jobs}

# Count total and completed jobs
total_jobs=$(wc -l < "$cmd_file" | tr -d ' ')
completed_jobs=$(find data/qc/fastp -type f -name "*.json" | wc -l | tr -d ' ')

echo "Progress summary for ${name_of_substrate}: ${completed_jobs}/${total_jobs} jobs completed."

# ───────────────────────────────────────────────
# Step 2: Run multiqc
# ───────────────────────────────────────────────

# create the destination directory if it does not exist
mkdir -p data/qc/multiqc/

# check to see that there are FastQC/fastp outputs to analyze
input_pattern="data/qc/fastp/${name_of_substrate}*"
found_files=$(find data/qc/fastp -maxdepth 1 -type f -name "${name_of_substrate}*" | wc -l)

if [ "$found_files" -eq 0 ]; then
    echo " No matching files found for pattern: ${input_pattern}"
    echo " MultiQC cannot run without valid input files."
    exit 1
fi

# now run the multiqc report
echo "Running MultiQC report for ${name_of_substrate}..."
multiqc data/qc/fastp/${name_of_substrate}* \
  --filename data/qc/multiqc/${name_of_substrate}_merged \
  --interactive \
  --force \

# handle success or failure
if [ $? -eq 0 ]; then
    echo -e "\n MultiQC completed successfully for ${name_of_substrate}."
    echo "📄 Output: data/qc/multiqc/${name_of_substrate}_merged.html"
else
    echo -e "\n MultiQC failed for ${name_of_substrate}."
    echo "Check input files in data/qc/fastp/ or permissions for data/qc/multiqc/."
    exit 1
fi

# ───────────────────────────────────────────────
# Step 3: Convert to FASTA
# ───────────────────────────────────────────────
# create the correct directory if it doesnt exist
mkdir -p data/meta/merged_read_paths/

# look for files generated by fastp
for cond in "${conditions[@]}"; do
    pattern="data/merged/${name_of_substrate}/*${cond}*"
    outfile="data/meta/merged_read_paths/${name_of_substrate}_${cond}_file_paths.txt"

# identify the file paths and count the number of replicates per condition
if [ "$(find data/merged/${name_of_substrate} -type f -name "*${cond}*" | wc -l)" -gt 0 ]; then
    grep -n '.*' <<< "$(ls data/merged/${name_of_substrate}/*${cond}*)" > "$outfile"
    echo "Created $outfile"
else
    echo "No files found for pattern: $pattern"
    > "$outfile"
fi
done

# ───────────────────────────────────────────────
# Step 4: Write FASTA files
# ───────────────────────────────────────────────

# create the directories if they dont already exist
mkdir -p "data/processed/${name_of_substrate}/"

# look for the file paths we created in the last step
for cond in "${conditions[@]}"; do
    echo "Converting ${name_of_substrate} ${cond} to FASTA..."
    input_list="data/meta/merged_read_paths/${name_of_substrate}_${cond}_file_paths.txt"

    if [ ! -s "$input_list" ]; then
        echo "No input file list found for ${cond} — skipping."
        continue
    fi

    while IFS=$':' read -r -a y; do
        rep_num=${y[0]}
        file=${y[1]}
        new_name="${name_of_substrate}_${cond}_rep${rep_num}.merged.fasta"
        zcat "$file" | sed -n '1~4s/^@/>/p;2~4p' > "data/processed/${name_of_substrate}/${new_name}"
        echo "Created ${new_name}"
    done < "$input_list"
done
